// layout.tsx
'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ModalProvider } from "@/contexts/ModalContext";
import { ReactNode } from "react";
import ModalComponent from "@/components/Modal";
import BookNowForm from "@/components/Forms/BookNowForm";

import toast, { Toaster } from 'react-hot-toast';
const myFont = localFont({
  src: [
    {
      path: "./fonts/Switzer-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Switzer-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Switzer-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Switzer-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
});

/* export const metadata: Metadata = {
  title: "Treepz",
  description: "Generated by create next app",
}; */

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="flex flex-col !bg-white">
          <ModalProvider>
            <NavBar />
            {children}
            <Footer />
            <ModalComponent title="Book Now & Contact us">
              <BookNowForm />
            </ModalComponent>
                        <Toaster/>
          </ModalProvider>
        </div>
      </body>
    </html>
  );
}
