// layout.tsx
"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { ModalProvider } from "@/contexts/ModalContext";
import { EventModalProvider } from "@/contexts/EventModalContext";
import { ReactNode } from "react";
import ModalComponent from "@/components/Modal";
import BookNowForm from "@/components/Forms/BookNowForm";
import EventModalComponent from "@/components/EventModal";
import toast, { Toaster } from "react-hot-toast";
import EventForm from "@/components/Forms/EventForm";
const myFont = localFont({
  src: [
    {
      path: "./fonts/Switzer-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Switzer-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/Switzer-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Switzer-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
});

/* export const metadata: Metadata = {
  title: "Treepz",
  description: "Generated by create next app",
}; */

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="flex flex-col !bg-white">
               <EventModalProvider>
          <ModalProvider>
            <NavBar />
            {children}
            <Footer />
                        <EventModalComponent title="Event Form">

              <EventForm />
                        </EventModalComponent>
            <ModalComponent title="Book Now & Contact us">
              <BookNowForm />
            </ModalComponent>
            <Toaster />
          </ModalProvider>
                    </EventModalProvider> 
        </div>
      </body>
    </html>
  );
}
